package com.yd.weather.config

object Constants {
    const val LOCATION_CITY_ID = "-66208439"
    const val YYYY_MM_DD = "yyyyMMdd"
    const val YYYY_MM_DD_HH = "yyyyMMddHH"

    const val MAX_CITY_LIST_LENGTH = 20

    const val CITY_MANAGER_ITEM_HEIGHT = 98

    const val CURRENT_CITY_ID = "CURRENT_CITY_ID"
    const val CURRENT_CITY_ID_LIST = "CURRENT_CITY_ID_LIST"
    const val CURRENT_WEATHER_CARD_SORT = "CURRENT_WEATHER_CARD_SORT"
    const val CURRENT_WEATHER_OBSERVES_CARD_SORT = "CURRENT_WEATHER_OBSERVES_CARD_SORT"
    const val CURRENT_DAILY_WEATHER_TYPE = "CURRENT_DAILY_WEATHER_TYPE"
    const val CURRENT_WEATHER_BG_MAP = "CURRENT_WEATHER_BG_MAP"
    const val LINE_CHART_DAILY_WEATHER = "LINE_CHART_DAILY_WEATHER"
    const val LIST_DAILY_WEATHER = "LIST_DAILY_WEATHER"
    const val ITEM_TYPE_WEATHER_HEADER = 0
    const val ITEM_TYPE_HOUR_WEATHER = 1
    const val ITEM_TYPE_DAILY_WEATHER = 2
    const val ITEM_TYPE_AIR_QUALITY = 3
    const val ITEM_TYPE_LIFE_INDEX = 4
    const val ITEM_TYPE_ALARMS = 5

    // 紫外线、湿度、体感、风向、日出日落、气压、可见度、未来40日天气
    const val ITEM_TYPE_OBSERVE = 6
    const val MAX_WEATHER_BG_COUNT = 6
    val DEFAULT_WEATHER_CARD_SORT = intArrayOf(
        this.ITEM_TYPE_WEATHER_HEADER,
        this.ITEM_TYPE_ALARMS,
        this.ITEM_TYPE_AIR_QUALITY,
        this.ITEM_TYPE_HOUR_WEATHER,
        this.ITEM_TYPE_DAILY_WEATHER,
        this.ITEM_TYPE_OBSERVE,
        this.ITEM_TYPE_LIFE_INDEX
    )
    const val ITEM_TYPE_OBSERVE_UV = 0
    const val ITEM_TYPE_OBSERVE_SHI_DU = 1
    const val ITEM_TYPE_OBSERVE_TI_GAN = 2
    const val ITEM_TYPE_OBSERVE_WD = 3
    const val ITEM_TYPE_OBSERVE_SUNRISE_SUNSET = 4
    const val ITEM_TYPE_OBSERVE_PRESSURE = 5
    const val ITEM_TYPE_OBSERVE_VISIBILITY = 6
    const val ITEM_TYPE_OBSERVE_FORECAST40 = 7
    val DEFAULT_WEATHER_OBSERVES_CARD_SORT = intArrayOf(
        this.ITEM_TYPE_OBSERVE_UV,
        this.ITEM_TYPE_OBSERVE_SHI_DU,
        this.ITEM_TYPE_OBSERVE_TI_GAN,
        this.ITEM_TYPE_OBSERVE_WD,
        this.ITEM_TYPE_OBSERVE_SUNRISE_SUNSET,
        this.ITEM_TYPE_OBSERVE_PRESSURE,
        this.ITEM_TYPE_OBSERVE_VISIBILITY,
        this.ITEM_TYPE_OBSERVE_FORECAST40
    )
}